// Generated by scripts/build-legacy-seed.ts from ../jalkaennustus/dump-plain-d11hgd41ejed91-202408181231.sql.
// Do not edit by hand. Re-run `pnpm build-legacy-seed` to refresh.

export interface LegacySeedGroup {
  username: string;
  passwordHash: string;
  legacyId: number;
}

export const legacyGroups: readonly LegacySeedGroup[] = [
  { username: "priitl", passwordHash: "$2a$10$xoEZVuXPAprLplLF52Rtw.TCqADCsFmThADU2sencXh7k48JUyfl2", legacyId: 5 },
  { username: "indrek", passwordHash: "$2a$10$P6x166ESXxjNuAKpsWslDeEpCNG0m1/PCA6NdhUOe9Lt4K7ewAkW6", legacyId: 6 },
  { username: "kommuun", passwordHash: "$2a$10$TZ.RnanJ1KNcRDNDQLZtZ.DrGb4clmgFfz7.xEswFZcZwHDgXzixO", legacyId: 10 },
  { username: "Tafkin", passwordHash: "$2a$10$ClV7zHqcpnRIaaK1gxWjQuv3VJFTNHA6rqvXhkG5wsZJj74Lyt62u", legacyId: 16 },
  { username: "mattias", passwordHash: "$2a$10$pBTs9AxngQ4efpDRFYtRV.cAFRgU7oAFLzlRG42Ava6MHPssywToy", legacyId: 8 },
  { username: "krisrei", passwordHash: "$2a$10$N5aPqqF5irVoQHDZwX/NPuNqdha/SdMaR9DJxbivCGQkQ.9siftca", legacyId: 15 },
  { username: "jaank", passwordHash: "$2a$10$CU3uK4NVAuMsdoUO6U1h.uD5kgrXFcFPSsR3knXQYtD5RMxz84.qy", legacyId: 12 },
  { username: "mowka", passwordHash: "$2a$10$ifw7c/5HNk51Z/I/2ech8O40gdR5J55oVnn8lEuWs8YlP.hCr38lu", legacyId: 9 },
  { username: "martti", passwordHash: "$2a$10$MoPOovjkNHD6JVyJzu5Ns.YL0LEe8OVQuvBrx8EYG.zjqc.Pu8IQi", legacyId: 13 },
  { username: "karina", passwordHash: "$2a$10$LBStIvsaoTDUQeAGSUOnhu8HCg9mB3K7WLj7jIh6.00jTbIOXp0VS", legacyId: 7 },
  { username: "testgroup", passwordHash: "$2a$10$b.fcdMDIlud/WXU8zbZPveb4elGOXJ7CZ5u/.7YaL4sZotvVHy3Cq", legacyId: 17 },
  { username: "NortRM", passwordHash: "$2a$10$ZdR9ROkXz1xLWaAuN08XbeZfyfaR/NA8c37V9AoRrPPiG4oA0izSC", legacyId: 4 },
  { username: "Shound", passwordHash: "$2a$10$y84T7JqwCn7s7MnM.XoL8OUEtk2OkFvEp07cW75y0tf/BAuHRMJh.", legacyId: 14 },
  { username: "tanel", passwordHash: "$2a$10$SpQS3XQvCT/9sf3hZuRh2uzLz9bW8G4LO5Q/hF90QMm7IqvazOtxK", legacyId: 1 },
  { username: "ats", passwordHash: "$2a$10$hKezno9x6RS0GLvIFhKSn.P2mFDxhawdodGxwzrjQKkvhxwnhYvBi", legacyId: 18 },
  { username: "mehed", passwordHash: "$2a$10$eGDbIpsCqBTwar13AXGbMeyO2VJLsZ0VHG3yUdfOkvlSD9fj8vpWa", legacyId: 3 },
];
