// Generated by scripts/build-legacy-seed.ts from ../jalkaennustus/dump-plain-d11hgd41ejed91-202408181231.sql.
// Do not edit by hand. Re-run `pnpm build-legacy-seed` to refresh.

export { legacyTournaments } from './tournaments';
export type { LegacySeedTournament } from './tournaments';
export { legacyGroups } from './groups';
export type { LegacySeedGroup } from './groups';
export { legacyUsers } from './users';
export type { LegacySeedUser } from './users';
export { legacyScores } from './scores';
export type { LegacySeedScore } from './scores';

export const legacyDataMeta = {
  "sourceDump": "../jalkaennustus/dump-plain-d11hgd41ejed91-202408181231.sql",
  "builtAt": "2026-05-31T12:45:45.195Z",
  "counts": {
    "tournaments": 7,
    "groups": 16,
    "users": 60,
    "scores": 155,
    "legacyUserResultRows": 185
  }
} as const;
