// Generated by scripts/build-legacy-seed.ts from ../jalkaennustus/dump-plain-d11hgd41ejed91-202408181231.sql.
// Do not edit by hand. Re-run `pnpm build-legacy-seed` to refresh.

export interface LegacySeedTournament {
  code: string;
  name: string;
  startsAt: string;
  endsAt: string;
  legacyId: number;
}

export const legacyTournaments: readonly LegacySeedTournament[] = [
  { code: "EM2012", name: "UEFA Euro 2012", startsAt: "2012-06-08", endsAt: "2012-07-01", legacyId: 1 },
  { code: "WC2014", name: "FIFA World Cup 2014", startsAt: "2014-06-12", endsAt: "2014-07-13", legacyId: 2 },
  { code: "EM2016", name: "UEFA Euro 2016", startsAt: "2016-06-10", endsAt: "2016-07-10", legacyId: 3 },
  { code: "WC2018", name: "FIFA World Cup 2018", startsAt: "2018-06-14", endsAt: "2018-07-15", legacyId: 4 },
  { code: "EM2020", name: "UEFA Euro 2020", startsAt: "2021-06-11", endsAt: "2021-07-11", legacyId: 5 },
  { code: "WC2022", name: "FIFA World Cup 2022", startsAt: "2022-11-20", endsAt: "2022-12-18", legacyId: 6 },
  { code: "EM2024", name: "UEFA Euro 2024", startsAt: "2024-06-14", endsAt: "2024-07-14", legacyId: 7 },
];
