// Generated by scripts/build-legacy-seed.ts from ../jalkaennustus/dump-plain-d11hgd41ejed91-202408181231.sql.
// Do not edit by hand. Re-run `pnpm build-legacy-seed` to refresh.

export interface LegacySeedUserGroup {
  username: string;
  /** ISO timestamp string from legacy user_groups.deleted_at, or null if active. */
  deletedAt: string | null;
}

export interface LegacySeedUser {
  legacyId: number;
  username: string;
  groups: readonly LegacySeedUserGroup[];
}

export const legacyUsers: readonly LegacySeedUser[] = [
  { legacyId: 1, username: "Mart", groups: [{"username":"NortRM","deletedAt":"2018-01-01 00:00:00"},{"username":"mehed","deletedAt":null},{"username":"tanel","deletedAt":null}] },
  { legacyId: 4, username: "Ints", groups: [{"username":"mehed","deletedAt":null},{"username":"tanel","deletedAt":null}] },
  { legacyId: 5, username: "Armo", groups: [{"username":"mehed","deletedAt":null},{"username":"tanel","deletedAt":null}] },
  { legacyId: 6, username: "Tann", groups: [{"username":"NortRM","deletedAt":null},{"username":"kommuun","deletedAt":null},{"username":"mehed","deletedAt":null},{"username":"tanel","deletedAt":null}] },
  { legacyId: 11, username: "Tarts", groups: [{"username":"mehed","deletedAt":null},{"username":"tanel","deletedAt":null}] },
  { legacyId: 13, username: "Martin", groups: [{"username":"mehed","deletedAt":null},{"username":"tanel","deletedAt":null}] },
  { legacyId: 14, username: "Rando", groups: [{"username":"mehed","deletedAt":"2015-12-03 16:46:01.339964"},{"username":"tanel","deletedAt":"2015-12-03 16:46:01.339964"}] },
  { legacyId: 18, username: "Kristo", groups: [{"username":"NortRM","deletedAt":"2018-01-01 00:00:00"}] },
  { legacyId: 19, username: "Priit", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 20, username: "Pets", groups: [{"username":"NortRM","deletedAt":"2018-01-01 00:00:00"}] },
  { legacyId: 21, username: "Sander", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 23, username: "Mauks", groups: [{"username":"mehed","deletedAt":null}] },
  { legacyId: 24, username: "Mike", groups: [{"username":"mehed","deletedAt":null}] },
  { legacyId: 25, username: "Igor", groups: [{"username":"NortRM","deletedAt":"2018-01-01 00:00:00"}] },
  { legacyId: 27, username: "Karina", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 28, username: "Jevgeni", groups: [{"username":"NortRM","deletedAt":"2018-01-01 00:00:00"}] },
  { legacyId: 29, username: "Natalja J.", groups: [{"username":"NortRM","deletedAt":"2018-01-01 00:00:00"}] },
  { legacyId: 30, username: "Ülle", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 31, username: "Mattias", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 32, username: "Natalia A.", groups: [{"username":"NortRM","deletedAt":"2018-01-01 00:00:00"}] },
  { legacyId: 33, username: "mowka", groups: [{"username":"mowka","deletedAt":null}] },
  { legacyId: 35, username: "Jevgeni T", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 36, username: "Kaiko", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 37, username: "Trevor", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 38, username: "Marko", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 39, username: "fhf", groups: [] },
  { legacyId: 40, username: "fhfhdfg", groups: [{"username":"tanel","deletedAt":"2017-11-12 14:49:26.129416"}] },
  { legacyId: 41, username: "gghg", groups: [{"username":"tanel","deletedAt":"2017-11-12 14:49:26.129416"}] },
  { legacyId: 42, username: "ffhfghfhg", groups: [{"username":"kommuun","deletedAt":"2017-11-12 14:49:26.129416"}] },
  { legacyId: 43, username: "Tiina", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 44, username: "legacy_user_44", groups: [{"username":"jaank","deletedAt":"2017-11-12 14:49:26.129416"}] },
  { legacyId: 45, username: "Jaan", groups: [{"username":"jaank","deletedAt":"2017-11-12 14:49:26.129416"}] },
  { legacyId: 46, username: "Jaan", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 47, username: "Külli", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 48, username: "Chrome Autofill", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 49, username: "Jaanika", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 50, username: "Martti", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 51, username: "Liis", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 52, username: "Andrus", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 53, username: "Trevor", groups: [{"username":"Shound","deletedAt":null}] },
  { legacyId: 54, username: "kristjanR", groups: [{"username":"krisrei","deletedAt":"2017-11-12 14:49:26.129416"}] },
  { legacyId: 55, username: "Mikk", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 56, username: "Kait", groups: [{"username":"Shound","deletedAt":null}] },
  { legacyId: 57, username: "Martin Ulst", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 58, username: "Igor", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 59, username: "Markus", groups: [{"username":"NortRM","deletedAt":null}] },
  { legacyId: 60, username: "Alrik", groups: [{"username":"Shound","deletedAt":null}] },
  { legacyId: 61, username: "Tafkin", groups: [{"username":"Tafkin","deletedAt":null}] },
  { legacyId: 62, username: "kristjanR", groups: [{"username":"krisrei","deletedAt":null}] },
  { legacyId: 63, username: "Tafkin", groups: [{"username":"Shound","deletedAt":null}] },
  { legacyId: 64, username: "Viljar", groups: [{"username":"Shound","deletedAt":null}] },
  { legacyId: 65, username: "Kristjaano ronaldo ", groups: [{"username":"Shound","deletedAt":null}] },
  { legacyId: 67, username: "testgroup", groups: [{"username":"testgroup","deletedAt":null}] },
  { legacyId: 69, username: "Ats", groups: [{"username":"mehed","deletedAt":null}] },
  { legacyId: 70, username: "Priit", groups: [{"username":"mehed","deletedAt":"2022-05-05 13:10:33.215218"}] },
  { legacyId: 71, username: "Rax", groups: [{"username":"mehed","deletedAt":null}] },
  { legacyId: 72, username: "ats", groups: [{"username":"ats","deletedAt":null}] },
  { legacyId: 73, username: "ChatGBT", groups: [{"username":"mehed","deletedAt":"2023-12-01 12:00:00"}] },
  { legacyId: 74, username: "TC_OPEN_AI", groups: [{"username":"mehed","deletedAt":"2023-12-01 12:00:00"}] },
  { legacyId: 75, username: "open_AI", groups: [{"username":"mehed","deletedAt":null}] },
];
