/**
 * Build-time tool that reads the legacy Rails 7 pg_dump and emits committed
 * seed-data modules under `db/seed-data/legacy/`. Run via:
 *
 *   pnpm build-legacy-seed [path/to/dump.sql]
 *
 * Output:
 *   - db/seed-data/legacy/{tournaments,groups,users,scores,index}.ts
 *   - docs/migration-reconciliation-<YYYY-MM-DD>.md
 *
 * Exit 0 when every (legacy_group, legacy_tournament) bucket reconciles
 * (legacy_rows == produced + excluded categories). Exit 1 otherwise.
 *
 * Pure Node: no DB connection here. The runtime seeder
 * (db/seed-data/legacy/index.ts → seedLegacy) is the one that touches the
 * database.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseCopyBlocks } from './legacy/dump-parser';
import {
  asLegacyGroups,
  asLegacyTournaments,
  asLegacyUserGroups,
  asLegacyUserResults,
  asLegacyUsers,
  HISTORICAL_TOURNAMENTS,
  SINGLETON_KEY,
  transformGroups,
  transformScores,
  transformUsers,
  type ReconciliationReport,
  type SeedGroup,
  type SeedScore,
  type SeedTournament,
  type SeedUser,
} from './legacy/transforms';

const DEFAULT_DUMP = '../jalkaennustus/dump-plain-d11hgd41ejed91-202408181231.sql';
const OUT_DIR = 'db/seed-data/legacy';
const DOCS_DIR = 'docs';

function logLine(level: 'info' | 'warn' | 'error', fields: Record<string, unknown>) {
  // eslint-disable-next-line no-console
  console.log(JSON.stringify({ ts: new Date().toISOString(), level, ...fields }));
}

function tsHeader(sourceDump: string): string {
  return `// Generated by scripts/build-legacy-seed.ts from ${sourceDump}.
// Do not edit by hand. Re-run \`pnpm build-legacy-seed\` to refresh.

`;
}

function emitTournaments(tournaments: SeedTournament[], sourceDump: string): string {
  const body = tournaments
    .map(
      (t) =>
        `  { code: ${JSON.stringify(t.code)}, name: ${JSON.stringify(t.name)}, startsAt: ${JSON.stringify(t.startsAt)}, endsAt: ${JSON.stringify(t.endsAt)}, legacyId: ${t.legacyId} },`,
    )
    .join('\n');
  return `${tsHeader(sourceDump)}export interface LegacySeedTournament {
  code: string;
  name: string;
  startsAt: string;
  endsAt: string;
  legacyId: number;
}

export const legacyTournaments: readonly LegacySeedTournament[] = [
${body}
];
`;
}

function emitGroups(groups: SeedGroup[], sourceDump: string): string {
  const body = groups
    .map(
      (g) =>
        `  { username: ${JSON.stringify(g.username)}, passwordHash: ${JSON.stringify(g.passwordHash)}, legacyId: ${g.legacyId} },`,
    )
    .join('\n');
  return `${tsHeader(sourceDump)}export interface LegacySeedGroup {
  username: string;
  passwordHash: string;
  legacyId: number;
}

export const legacyGroups: readonly LegacySeedGroup[] = [
${body}
];
`;
}

function emitUsers(users: SeedUser[], sourceDump: string): string {
  const body = users
    .map(
      (u) =>
        `  { legacyId: ${u.legacyId}, username: ${JSON.stringify(u.username)}, groupUsernames: ${JSON.stringify(u.groupUsernames)} },`,
    )
    .join('\n');
  return `${tsHeader(sourceDump)}export interface LegacySeedUser {
  legacyId: number;
  username: string;
  groupUsernames: readonly string[];
}

export const legacyUsers: readonly LegacySeedUser[] = [
${body}
];
`;
}

function emitScores(scores: SeedScore[], sourceDump: string): string {
  const body = scores
    .map((s) => {
      const userKey =
        s.userKey === SINGLETON_KEY ? `'singleton'` : String(s.userKey);
      return `  { groupUsername: ${JSON.stringify(s.groupUsername)}, tournamentCode: ${JSON.stringify(s.tournamentCode)}, userKey: ${userKey}, totalPoints: ${s.totalPoints}, finishingPosition: ${s.finishingPosition} },`;
    })
    .join('\n');
  return `${tsHeader(sourceDump)}/**
 * userKey: legacy user_id for non-singleton users; 'singleton' for the
 * tegelikud-tulemused remap (Constitution Critical Rule 1).
 */
export interface LegacySeedScore {
  groupUsername: string;
  tournamentCode: string;
  userKey: number | 'singleton';
  totalPoints: number;
  finishingPosition: number;
}

export const legacyScores: readonly LegacySeedScore[] = [
${body}
];
`;
}

function emitIndex(meta: {
  sourceDump: string;
  builtAt: string;
  counts: Record<string, number>;
}): string {
  return `// Generated by scripts/build-legacy-seed.ts from ${meta.sourceDump}.
// Do not edit by hand. Re-run \`pnpm build-legacy-seed\` to refresh.

export { legacyTournaments } from './tournaments';
export type { LegacySeedTournament } from './tournaments';
export { legacyGroups } from './groups';
export type { LegacySeedGroup } from './groups';
export { legacyUsers } from './users';
export type { LegacySeedUser } from './users';
export { legacyScores } from './scores';
export type { LegacySeedScore } from './scores';

export const legacyDataMeta = ${JSON.stringify(meta, null, 2)} as const;
`;
}

function emitReconciliationMarkdown(
  report: ReconciliationReport,
  sourceDump: string,
  builtAt: string,
): string {
  const lines: string[] = [];
  lines.push('# Legacy migration reconciliation report');
  lines.push('');
  lines.push(`- **Source dump:** \`${sourceDump}\``);
  lines.push(`- **Built at:** ${builtAt}`);
  lines.push(`- **Outcome:** ${report.ok ? '**RECONCILIATION: OK**' : `**RECONCILIATION: FAIL** (${report.cells.filter((c) => !c.balanced).length} unbalanced cells)`}`);
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  lines.push('| Category | Count |');
  lines.push('|----------|------:|');
  lines.push(`| Legacy user_results rows | ${report.totals.legacyRows} |`);
  lines.push(`| Produced legacy_tournament_scores rows | ${report.totals.produced} |`);
  lines.push(`| Excluded — NULL points | ${report.totals.excludedNullPoints} |`);
  lines.push(`| Collapsed — duplicate singleton / same-user rows | ${report.totals.collapsedSingletonDuplicates} |`);
  lines.push(`| Orphan user_group refs | ${report.totals.orphanRefs} |`);
  lines.push(`| Unknown tournament | ${report.totals.unknownTournament} |`);
  lines.push('');
  lines.push('Balance: `legacyRows == produced + excludedNullPoints + collapsedSingletonDuplicates + orphanRefs + unknownTournament` per cell.');
  lines.push('');
  lines.push('## Per (group, tournament) breakdown');
  lines.push('');
  lines.push('| Group | Tournament | Legacy rows | Produced | NULL points | Collapsed | Orphan | Unknown | Balanced |');
  lines.push('|-------|------------|------------:|---------:|------------:|----------:|-------:|--------:|:--------:|');
  for (const c of report.cells) {
    lines.push(
      `| ${c.groupUsername} | ${c.tournamentCode} | ${c.legacyRows} | ${c.produced.count} | ${c.excludedNullPoints.count} | ${c.collapsedSingletonDuplicates.count} | ${c.orphanRefs.count} | ${c.unknownTournament.count} | ${c.balanced ? '✓' : '✗'} |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

function main(): number {
  const dumpArg = process.argv[2] ?? DEFAULT_DUMP;
  const dumpAbsPath = resolve(process.cwd(), dumpArg);
  const builtAt = new Date().toISOString();
  const dateForReport = builtAt.slice(0, 10);

  logLine('info', { operation: 'build_legacy_seed', step: 'read', dump: dumpAbsPath });
  const dumpText = readFileSync(dumpAbsPath, 'utf8');

  const blocks = parseCopyBlocks(dumpText, [
    'tournaments',
    'groups',
    'users',
    'user_groups',
    'user_results',
  ]);
  const required: ReadonlyArray<string> = ['tournaments', 'groups', 'users', 'user_groups', 'user_results'];
  for (const t of required) {
    if (!blocks.has(t)) {
      logLine('error', {
        operation: 'build_legacy_seed',
        outcome: 'error',
        message: `Dump is missing required COPY block for public.${t}`,
      });
      return 1;
    }
  }

  const legacyTournaments = asLegacyTournaments(blocks.get('tournaments')!);
  const legacyGroups = asLegacyGroups(blocks.get('groups')!);
  const legacyUsers = asLegacyUsers(blocks.get('users')!);
  const legacyUserGroups = asLegacyUserGroups(blocks.get('user_groups')!);
  const legacyUserResults = asLegacyUserResults(blocks.get('user_results')!);

  // Sanity: every legacy tournament id must have a historical mapping.
  for (const t of legacyTournaments) {
    if (!HISTORICAL_TOURNAMENTS[t.id]) {
      logLine('warn', {
        operation: 'build_legacy_seed',
        message: `Legacy tournament ${t.id} (${t.name}) not in HISTORICAL_TOURNAMENTS — its results will be skipped`,
      });
    }
  }

  const tournamentCodeById = new Map<number, string>();
  const tournamentsOut: SeedTournament[] = [];
  for (const t of legacyTournaments) {
    const mapped = HISTORICAL_TOURNAMENTS[t.id];
    if (!mapped) continue;
    tournamentCodeById.set(t.id, mapped.code);
    tournamentsOut.push(mapped);
  }
  tournamentsOut.sort((a, b) => a.legacyId - b.legacyId);

  const groupsOut = transformGroups(legacyGroups);
  const groupUsernameById = new Map<number, string>();
  for (const g of legacyGroups) groupUsernameById.set(g.id, g.username);

  const { users: usersOut, userKeyByLegacyId } = transformUsers(
    legacyUsers,
    legacyUserGroups,
    groupUsernameById,
  );

  const { scores, report } = transformScores({
    results: legacyUserResults,
    userGroups: legacyUserGroups,
    legacyUserKeyByLegacyId: userKeyByLegacyId,
    legacyGroupUsernameById: groupUsernameById,
    legacyTournamentCodeById: tournamentCodeById,
  });

  const sourceDump = dumpArg;
  const counts = {
    tournaments: tournamentsOut.length,
    groups: groupsOut.length,
    users: usersOut.length,
    scores: scores.length,
    legacyUserResultRows: legacyUserResults.length,
  };
  const meta = { sourceDump, builtAt, counts };

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, 'tournaments.ts'), emitTournaments(tournamentsOut, sourceDump));
  writeFileSync(join(OUT_DIR, 'groups.ts'), emitGroups(groupsOut, sourceDump));
  writeFileSync(join(OUT_DIR, 'users.ts'), emitUsers(usersOut, sourceDump));
  writeFileSync(join(OUT_DIR, 'scores.ts'), emitScores(scores, sourceDump));
  writeFileSync(join(OUT_DIR, 'index.ts'), emitIndex(meta));

  mkdirSync(DOCS_DIR, { recursive: true });
  const reportPath = join(DOCS_DIR, `migration-reconciliation-${dateForReport}.md`);
  writeFileSync(reportPath, emitReconciliationMarkdown(report, sourceDump, builtAt));

  logLine('info', {
    operation: 'build_legacy_seed',
    outcome: report.ok ? 'ok' : 'fail',
    counts,
    totals: report.totals,
    report: reportPath,
  });

  if (report.ok) {
    // eslint-disable-next-line no-console
    console.log('RECONCILIATION: OK');
    return 0;
  } else {
    const failed = report.cells.filter((c) => !c.balanced).length;
    // eslint-disable-next-line no-console
    console.log(`RECONCILIATION: FAIL ${failed}`);
    return 1;
  }
}

try {
  process.exit(main());
} catch (err) {
  logLine('error', {
    operation: 'build_legacy_seed',
    outcome: 'error',
    message: err instanceof Error ? err.message : String(err),
    stack: err instanceof Error ? err.stack : undefined,
  });
  process.exit(1);
}
